apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-deployment
  labels:
    app: product
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
      - name: product
        image: younusansari/product-service:latest
        ports:
        - containerPort: 3001
        resources:
          limits:
            cpu: "1"
          requests:
            cpu: "0.5"