apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
  labels:
    app: order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
      - name: order
        image: younusansari/order-service:latest
        ports:
        - containerPort: 3002
        resources:
          limits:
            cpu: "1"
          requests:
            cpu: "0.5"